### ISSUE TITLE
Admin subscription still issuing confirmation request

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/MyGovBC-notification-server#15]
Hi, this is chris from the devex.

Before the update that fixed the templating on notifications, we were subscribing users to lists and immediately setting them to confirmed.  I assume this worked fine because we hit the server from an admin IP.  We are still performing the exact same call, but all subscriptions are set to unconfirmed and a message is sent to the user asking them to enter the number on the screen (but there is no screen and nowhere to enter it so I assume we would have to build that endpoint on ours).

Is this change intentional? Is there some way we can skip the confirmation step as we were before? It is a superfluous step for us.

Thanks.

**Comment by f-w** [comment]
Hi Chris,
Do you know the git SHA-1 you are using?
One possible cause is some config re-arrangements I made recently. I can confirm setting state to *unconfirmed* is a bug and have fixed it in latest commit ddc332440ad4eb3c689067d75235e55a9e2f73ae.

**Comment by ccoldwell** [comment]
git rev-parse HEAD gives me this:

93121f209ce291df6bf3b68118c86dc0bbe4a33a

I will take a new copy, thanks

**Comment by f-w** [comment]
You need to set field *confirmationRequest.sendRequest* to false in your subscription request as documented in subscription api to avoid sending confirmation request email. I believe the *unconfirmed* bug exists in your version so using the latest copy is advised. Please review [configuration](https://bcgov.github.io/MyGovBC-notification-server/docs/configuration/) doc for potential breaking changes, in particular the subscription section.

**Comment by ccoldwell** [comment]
thanks!
