### ISSUE TITLE
make mongodb in os a cluster

### ISSUE THREAD

**Issue by f-w** [bcgov/MyGovBC-notification-server#19]

**Comment by GregTurner** [comment]
FYI, Mongo in cluster on OS is something that was on @kelpisland list of tools to consider investing in.  He may have done some work already in this space.

**Comment by f-w** [comment]
I did some preliminary R&D. It will take more effort than ElasticSearch. In ES, a cattle node can join a cluster by setting a discovery URL - service in case of os, in its config. MongoDB seems still treating nodes as pets.
