### ISSUE TITLE
What is the average latency of using government smtp server?

### ISSUE THREAD

**Issue by GregTurner** [bcgov/MyGovBC-notification-server#26]
In your experience with NotifyBC, what is the average time it takes to deliver emails outside of .gov.bc.ca addresses?

**Comment by f-w** [comment]
See [benchmarks](https://bcgov.github.io/MyGovBC-notification-server/docs/benchmarks/). Yours is more of a question to smtp server rather than to NotifyBC. app.smtp.gov.bc.ca imposes a significantly low throughput by guideline.

**Comment by GregTurner** [comment]
@f-w so does NotifyBC use it's own SMTP relay?

**Comment by f-w** [comment]
You can config it to use SMTP server, which is preferred in prod. By default it acts as the SMTP server itself.

**Comment by GregTurner** [comment]
I heard rumors of the apps.smtp.gov.bc.ca sometimes gets slow, have you noticed that?

**Comment by f-w** [comment]
*NotifyBC* doesn't depend on apps.smtp.gov.bc.ca specifically so the question is a little off the topic. If a list has many subscribers, then the service provider is expected do their capacity planning and setup their own smtp server if needed, which is the case for a popular mailing list app I involved before.

**Comment by GregTurner** [comment]
Thanks Fred.  I'll close it now.
