### ISSUE TITLE
Clarification on admin access

### ISSUE THREAD

**Issue by cgat** [bcgov/MyGovBC-notification-server#3]
To quote the documentation:

> 
> NotifyBC, designed to be a microservice, doesn’t use ACL to secure API calls. Instead, it classifies incoming requests into admin and user types according to following criteria:
> 
> If the request bears SiteMinder header, it is a user request;
> If the source ip is in the admin ip list, it’s an admin request.
> An admin request carries full authorization whereas user request has limited access. 

I'm attempting to set up this to be used with BCDevExchange to notify users of new opportunities. Based on the above documentation, my expectation is that an ip address listed in the `adminIps` whitelist should have full access to the RESTful endpoints. However, it seems some operations (subscription deletion, for example) do not have access without SiteMinder authentication.

More specifically, here is the chunk of code that blocks `delete` access

```
Subscription.beforeRemote('prototype.deleteItemById', function (ctx, unused, next) {
    var u = Subscription.app.models.Notification.getCurrentUser(ctx) || 'unknown'
    if (ctx.instance.userId === u) {
      return next()
    }
    var error = new Error('Forbidden')
    error.status = 403
    next(error)
  })
```

`Notification.isAdminReq` is never called, while `getCurrentUser` only checks SiteMinder authorization. 

I believe this happens in a couple other places.

Is this the expected behaviour and if so, is it generally considered secure to use the `admin ip whitelist` approach to use this service?

I'm willing to create a pull request if need be.

**Comment by f-w** [comment]
@cgat, the description in Overview is my intention. The app is still in development phase so the issues you discovered could well be a bug and pr is much appreciated.

**Comment by cgat** [comment]
@f-w PR is here https://github.com/bcgov/MyGovBC-notification-server/pull/4

Let me know what you think. If you aren't a fan of how I've restructured things in regards to access control, I can make a less invasive change (changing the function I mentioned above). I can also make a similar change to notifications end point if you like how I've organized authorization on the subscription side.

**Comment by f-w** [comment]
I have reviewed all REST API endpoints and I believe access control are all in place.
Methods common to all models have been refactored into mixins as side-effect.
